# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "indirect"
      - dependency-type: "direct"
    ignore:
      - dependency-name: "@angular/animations"
      - dependency-name: "@angular/cdk"
      - dependency-name: "@angular/common"
      - dependency-name: "@angular/compiler"
      - dependency-name: "@angular/core"
      - dependency-name: "@angular/elements"
      - dependency-name: "@angular/forms"
      - dependency-name: "@angular/material"
      - dependency-name: "@angular/platform-browser"
      - dependency-name: "@angular/platform-browser-dynamic"
      - dependency-name: "@angular/router"
      - dependency-name: "rxjs"
      - dependency-name: "sass"
      - dependency-name: "tslib"
      - dependency-name: "@angular-devkit/build-angular"
      - dependency-name: "@angular-devkit/core"
      - dependency-name: "@angular-devkit/schematics"
      - dependency-name: "@angular/cli"
      - dependency-name: "@angular/compiler-cli"
      - dependency-name: "@angular/language-service"
      - dependency-name: "@types/d3"
      - dependency-name: "@types/jasmine"
      - dependency-name: "@types/jasminewd2"
      - dependency-name: "@types/jspdf"
      - dependency-name: "@types/node"
      - dependency-name: "fs-extra"
      - dependency-name: "ng-packagr"
      - dependency-name: "ts-node"
      - dependency-name: "typescript"