
export let friendlyFeaturesName = new Map<string, string>([
    ['NAME', 'Names'],
    ['ADDRESS', 'Addresses'],
    ['EMAIL', 'Emails'],
    ['PHONE', 'Phone Numbers'],
    ['PASSPORT', 'Passports'],
    ['DOB','Date of Birth'],
    ['ACCT_NUM','Account #'],
    ['DOD','DOD'],
    ['SSN','SSN'],
    ['DRLIC', 'Drivers License'],
    ['ACCT_NUM', 'Account Numbers'],
    ['LOGIN_ID', 'Logins'],
    ['TAX_ID', 'Tax ID\'s'],
    ['GEO_LOC', 'Geo Location'],
    ['WEBSITE', 'Websites'],
    ['VEH_VIN', 'VIN'],
    ['VEH_LIC_PLATE', 'License Plate'],
    ['PLACE_OF_BIRTH', 'Birthplace'],
    ['RECORD_TYPE', 'Record Type'],
    ['OTHER_ID', 'Other ID'],
    ['TRUSTED_ID', 'Trusted ID'],
    ['REGISTRATION_DATE', 'Registered On'],
    ['REGISTRATION_COUNTRY', 'Registered In'],
    ['DUNS_NUMBER', 'DUNS'],
    ['NPI_NUMBER', 'NPI'],
    ['LEI_NUMBER', 'LEI']
]);
